POC/LogAnalyzer/log_pro/log_app/urls.py
from django.urls import path
from log_app import views
app_name = "log_app"

urlpatterns = [
    path('',views.IndexView.as_view(),name="index"),
    path('analyze_log',views.AzlogView,name="azlog"),
    path('analyze_site',views.AzsiteView.as_view(),name="azsite"),
]

POC/LogAnalyzer/log_pro/log_pro/urls.py
from django.contrib import admin
from django.urls import path,include
from log_app import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.IndexView.as_view(),name="index"),
    path('log_app/',include("log_app.urls",namespace="log_app")),
]

POC/LogAnalyzer/log_pro/log_app/models.py
from django.db import models

# Create your models here.

POC/LogAnalyzer/log_pro/log_app/forms.py
from django import forms



class AnalyzeLog_Form(forms.Form):
    log_file = forms.FileField()

POC/LogAnalyzer/log_pro/log_app/views.py
from django.shortcuts import render
from log_app.forms import AnalyzeLog_Form
from django.views.generic import TemplateView
# Create your views here.

def AzlogView(request):
    form = AnalyzeLog_Form()
    if request.method == 'POST':
        form = AnalyzeLog_Form(request.POST)
        print("validation success1")
        if form.is_valid():
            print("validation success2")
            print(form.cleaned_data['log_file'])
    form_dict = {'form': form}
    return render(request, 'log_app/analyze_log.html', form_dict)


class IndexView(TemplateView):
    template_name = "log_app/index.html"

# class AzlogView(TemplateView):
#     template_name = "log_app/analyze_log.html"

class AzsiteView(TemplateView):
    template_name = "log_app/analyze_site.html"

POC/LogAnalyzer/log_pro/templates/log_app/analyze_log.html
<!DOCTYPE html>
{% extends "log_app\common_style.html" %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1 class="display-4">Welcome to Log Analyzer</h1>
      <p class="lead">This tool is used to scrape logs generated by applications and servers to obtain useful informations.</p>
      <hr class="my-4">
      <p>This utility uses custom python function called progrep to extract the required informations.</p>
      <div class="container">
      <div class="jumbotron">
        <div class="input-group">
          <div class="custom-file">
            <form method="post">
            {{form.as_p}}
            <input type="submit" class="btn btn-primary" value="Submit">
            {%csrf_token%}
        </form>
          </div>
        </div>
      </div>
      </div>
    </div>
  </div>
{% endblock %}

POC/LogAnalyzer/log_pro/templates/log_app/analyze_site.html
<!DOCTYPE html>
{% extends "log_app\common_style.html" %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1 class="display-4">Welcome to Site Analyzer</h1>
      <p class="lead">This tool is used to scrape scrape webistes to obtain useful informations.</p>
      <hr class="my-4">
      <p>This utility uses custom python function called progrep to extract the required informations.</p>

      <div class="input-group">
        <div class="custom-file">
          <input type="text" class="form-control" id="Analyzelable" placeholder="Enter URL to Scrap">
        </div>
        <div class="input-group-append">
          <button class="btn btn-info" type="button" id="inputGroupFileAddon04">Analyze</button>
        </div>
      </div>

    </div>
  </div>
{% endblock %}

POC/LogAnalyzer/log_pro/templates/log_app/common_style.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href={% static "bootstrap-4.1.3-dist/css/bootstrap.min.css" %}>
    <script src="{% static "custom_js/jquery-3.3.1.js"%}" defer></script>
    <script src="{% static "custom_js/analyzelog.js"%}" defer></script>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <a class="navbar-brand" href="#">
          <img src={% static "images/lens.png" %} width="30" height="30" alt="">
        </a>
        <a class="navbar-brand" href="{% url "log_app:index"%}">Home</a>
        <a class="navbar-brand" href="{% url "log_app:azlog"%}">Analyze Log</a>
        <a class="navbar-brand" href="{% url "log_app:azsite"%}">Analyze Site</a>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <a class="navbar-brand" href="{% url "admin:index" %}">Site Admin</a>
    </form>
  </div>
</nav>
  {% block body_block %}
  {% endblock %}
</body>
</html>

POC/LogAnalyzer/log_pro/templates/log_app/index.html
<!DOCTYPE html>
{% extends "log_app\common_style.html" %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1 class="display-4">Welcome to Pro Analyzer</h1>
      <p class="lead">This tool is used to scrape logs generated by applications and servers and also used to scrape webistes to obtain useful informations.</p>
      <hr class="my-4">
      <p>This utility uses custom python function called progrep to extract the required informations.</p>
      <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
    </div>
  </div>
{% endblock %}